preset: conventionalcommits
branches:
  - name: master
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"

  # This creates fancy release notes in our Github release
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
