name: gobox
reportingTeam: fnd-dtss
description: Open source general go functions
oss: true
slack: dev-tooling-notifications
library: true
circleAPIKey: ""
releaseType: semver
releaseOptions:
  allowPrereleases: false
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  dependencies:
    optional: []
    required: []
  description: Open source general go functions
  opslevel:
    confluenceSpaceKey: ""
    designDocumentLink: ""
  oss: true
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
