name: gobox
reportingTeam: fnd-dtss
description: A collection of libraries that are useful for implementing Go services, libraries, and more.
oss: true
slack: dev-tooling-notifications
library: true
circleAPIKey: ""
releaseType: semver
releaseOptions:
  allowPrereleases: false
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands: []
  dependencies:
    optional: []
    required: []
  description: A collection of libraries that are useful for implementing Go services, libraries, and more.
  grpcClients: []
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: false
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - name: github.com/getoutreach/stencil-base
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
