// Code generated by "stringer -type=StatusCode"; DO NOT EDIT.

package statuscodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-600]
	_ = x[BadRequest-700]
	_ = x[Unauthorized-701]
	_ = x[Forbidden-702]
	_ = x[NotFound-703]
	_ = x[Conflict-704]
	_ = x[RateLimited-705]
	_ = x[ClientConnectionSevered-706]
	_ = x[InternalServerError-800]
	_ = x[NotImplemented-801]
	_ = x[Unavailable-802]
	_ = x[UnknownError-803]
	_ = x[DeadlineExceeded-804]
}

const (
	_StatusCode_name_0 = "OK"
	_StatusCode_name_1 = "BadRequestUnauthorizedForbiddenNotFoundConflictRateLimitedClientConnectionSevered"
	_StatusCode_name_2 = "InternalServerErrorNotImplementedUnavailableUnknownErrorDeadlineExceeded"
)

var (
	_StatusCode_index_1 = [...]uint8{0, 10, 22, 31, 39, 47, 58, 81}
	_StatusCode_index_2 = [...]uint8{0, 19, 33, 44, 56, 72}
)

func (i StatusCode) String() string {
	switch {
	case i == 600:
		return _StatusCode_name_0
	case 700 <= i && i <= 706:
		i -= 700
		return _StatusCode_name_1[_StatusCode_index_1[i]:_StatusCode_index_1[i+1]]
	case 800 <= i && i <= 804:
		i -= 800
		return _StatusCode_name_2[_StatusCode_index_2[i]:_StatusCode_index_2[i+1]]
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
